# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.1

EAPI="3"
SUPPORT_PYTHON_ABIS="1"

inherit distutils


DESCRIPTION="Format dates according to the RFC 3339."
HOMEPAGE="http://pypi.python.org/pypi/rfc3339/"
SRC_URI="http://pypi.python.org/packages/source/r/rfc3339/${P}.tar.gz"

LICENSE=""
KEYWORDS="~x86"
SLOT="0"
IUSE=""

DEPEND="dev-python/setuptools"
RDEPEND="${DEPEND}"


